name: Setup
description: Sets up the job
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1.1.1
      with:
        bun-version: 1.0.29
    - name: Install dependencies
      shell: bash
      run: bun install
    - name: Setup git-cliff
      uses: kenji-miyake/setup-git-cliff@v2.0.0
      with:
        version: 2.0.4
