# Reusable workflow for packaging a nightly release
name: _Package nightly release

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.package.outputs.version }}
        description: "Version of the packaged extension"

jobs:
  package:
    name: Package nightly release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Retrieve pre-compiled extension assets
        uses: actions/cache/restore@v4
        with:
          path: out/
          key: compiled-extension-${{ github.sha }}
      
      - name: Patch package.json version
        run: bun scripts/patch-version.ts

      - name: Read version from package.json
        id: version
        run: echo "version=$(jq -r '.version' package.json)" >> "$GITHUB_OUTPUT"

      - name: Package nightly extension
        run: bun vsce package --pre-release -o git-reminder-nightly.vsix
    
      - name: Upload nightly extension artifacts
        uses: actions/upload-artifact@v4
        with:
          name: git-reminder-nightly.vsix
          path: git-reminder-nightly.vsix

    outputs:
      version: ${{ steps.version.outputs.version }}  